apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-simple-app
  labels:
    app: flask-simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-simple-app
  template:
    metadata:
      labels:
        app: flask-simple-app
    spec:
      containers:
      - name: flask
        image: registry.gitlab.com/israelsz/appexample:d8e9ab959ca8c7c030038bb96e2df40ed5913bf9
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
