apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-simple-app
  labels:
    app: flask-simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-simple-app
  template:
    metadata:
      labels:
        app: flask-simple-app
    spec:
      containers:
      - name: flask
        image: registry.gitlab.com/israelsz/appexample:417294e0a427506e5cc5b4a572cf06f7f6e98dcf
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
