---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      namespace: argocd
      name: argocd-tls
      jsonPointers:
        - /status
        - /metadata/ownerReferences
        - /metadata/annotations

  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.2
      helm:
        valueFiles:
          - $values/app-config/cert-manager/values.yaml
          
    - repoURL: https://github.com/israelsz/homelab.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/israelsz/homelab.git
      targetRevision: main
      path: app-config/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true