apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-simple-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/israelsz/homelab.git
    targetRevision: main
    path: app-config/flask-simple-app
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-simple-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true