apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/israelsz/homelab.git
    targetRevision: main
    path: app-config/local-path-provisioner
  
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
