apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
patch: |
  data:
    url: https://argocd.macrohard.software
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.macrohard.software/realms/argo-test
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
