apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.macrohard.software
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.macrohard.software/realms/argo-test
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  oidc.keycloak.clientSecret: $argocd-oidc-secret:oidc.keycloak.clientSecret
