apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  suspend: true
  secretName: argocd-tls       
  issuerRef:
    name: letsencrypt-prod     
    kind: ClusterIssuer
  commonName: argocd.macrohard.software
  dnsNames:
    - argocd.macrohard.software
