apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress.yaml

patches:
  - path: argocd-keycloak-cm-patch.yaml
  - path: argocd-keycloack-rbac-cm-patch.yaml
  - path: sealedsecret-argocd-secret.yaml
