apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Create namespace for argocd
  - ns.yaml
  # Install ArgoCD
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml

patchesStrategicMerge:
  - argocd-keycloak-cm-patch.yaml
  - argocd-keycloack-rbac-cm-patch.yaml
  - sealedsecret-argocd-secret.yaml
