apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - postgres-sealed-secret.yaml
  - postgres-cluster.yaml
  - keycloak-db-sealed-secret.yaml
  - keycloak.yaml
  - ingress.yaml
