apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - postgres-secret.yaml
  - postgres-cluster.yaml
  - keycloak-db-secret.yaml
  - keycloak.yaml
  - certificate.yaml
  - ingress.yaml
