---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgAteFHGGlaOi+wPc8wfuGQjjMm2bVlJVNfgX4HHmvpSYSgDtbpVqzuCTHT3dI81SVxXMC2UbpepUNi2LugRU+Vqr7euJo2HQhGhHgnCKLLhM5mDZ75Tz4bv1b8nuc92uYMRmyQoU23IiYS5lLt/2SkpGcBG7uEh8V9dGdSOK2dufiwURzglgjVJqD6PtoZ1Nna8HwU7icIb05mX2nZbwDKW5Xu/vI4+theq5ceffafCa8lg9Z9Kh+ukqWys9NTZgqkN0E+uR1xTCYlwc433AkmI+HGTrneG4fBPgQmshLXHh4artxK2APK+z5HdFevKQyqE8j482P5H7NmkevsGg2B+mIHe3itn1hiL1a3Oi/rcUttafEoEpmrl8ZijqpPmeDVARUrTe+k4Gf8EpirEqhX0HiK+W/waxaeGD5drKtzhl3Rqs52kmyVvT1w0hzZgdFjWQKrHQYx/Sa6LID1sS+MKqRgAejc+ZeN+XU9R/qx8rn0Ae0hSwZ0/1KqvvIlm27VLDpKOnoroXZocs+tsHP/zKj4KC8HA949FDD6dT87pA5uWvGGkAc345XWlhGLEarp6Q9ktc/ZIa62oMA2DkdlNBUln5JwSAMfbiByL5t2HbyFH26Y5gDw7gCKo6Mm2Ml5tl2uSz5O1/6XSltfZOVfXaaXXLS5ix8k9Z+c5NH1JEQurh0Zfgp861OF6xjQRvU1MgMSz3gVy
    username: AgB4CPae4nRYONhfTFWWjL5wK2fvsbxPaNZRawMPBXvgzTFXngzbQhJbYUzbpFWdPU74S5/9A6fR7vnK4H9PqHMVGQT5DbQV7OOba4YOgISl3CUjc+n4Jfv6vYgpjrDKYf6ByeB+gD/Frj4lMTKioGIKaYl/2wnnKJ7xS0JrlI/Y5kC6Pv9ppqZ3CW9KXyH3y2k9j/jwNJMJniX9R27tpEpQwdMdNeJPWIqnZAL1lAB0qyz9Bs3OK9lwaQN3oH58uVj0L1iNJaHYdHM2Rc43tjBmnYorAmTr3vzRRxTNYsVtTLHzdC+iR3WVdG6K2WTX1MyRm7oHlNeK2QJipTkTaE+kFdt40hhDEHxdxVvO9yq0vtgxWWjL7Gcczy09qj9q2TlpMw4bBCW5TFGTOcngfXZSpZVPKaJtudFS6/FjsavHIN48kBEqI/YZzcNRlHeGx84OwK91sx0Gwj2A84CKXXNlKvNSZFLSn1Og/NW4Jd8tfim6mbSABjvKi4UEsfbBtOz21aCFbxGIx3YLHHCahqPwEUfajBg3lgDvSu+9k5gZubtsSI0s1PWRIP1gESIYTGOYDEz3DzivjZr30rk/dXQMpkErdXtkA2ddrYL7sUFhUsYyhtrvyazLAF/7CLW46HN0tGZpYdxghhQLT7Qd5W7TsvqyqphiOBFi+xY6w1D7Qwi2232QhWWW3R0Ydu7OW5UYbku25toFzw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-credentials
      namespace: keycloak
